version: "2"
linters:
  enable:
    - misspell
    - revive
    - gosec
  settings:
    revive:
      rules:
        - name: unused-parameter
          severity: warning
          disabled: true
    gosec:
      excludes:
        - G115
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - typecheck
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
